apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "albert-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: streamlit
spec:
  selector:
    app: streamlit
  ports:
    - port: {{ .Values.streamlit.service.port }}
      targetPort: 8501
      name: http
  type: {{ .Values.streamlit.service.type }}